import {
  CustomJwtPayloadDoctor,
  CustomJwtPayloadMember,
} from "@/libs/types/customJwtPayload";
import { makeVar } from "@apollo/client";
export const themeVar = makeVar({});

export const userVar = makeVar<CustomJwtPayloadMember>({
  _id: "",
  memberType: "",
  memberStatus: "",
  memberPhone: "",
  memberNick: "",
  memberFullName: "",
  memberImage: "",
  memberAddress: "",
  memberDesc: "",
  memberGender: "",
  memberArticles: 0,
  memberLikes: 0,
  memberViews: 0,
  memberWarnings: 0,
  memberBlocks: 0,
  isActive: true,
  lastLogin: null,
  bloodGroup: "",
  allergies: [""],
  chronicDiseases: [""],
  emergencyContact: "",
});

export const doctorVar = makeVar<CustomJwtPayloadDoctor>({
  _id: "",
  memberType: "",
  memberStatus: "",
  totalPatients: 0,
  memberPhone: "",
  memberNick: "",
  memberFullName: "",
  memberImage: "",
  memberAddress: "",
  memberDesc: "",
  memberGender: "",
  memberArticles: 0,
  memberLikes: 0,
  memberViews: 0,
  memberWarnings: 0,
  memberBlocks: 0,
  licenseNumber: "",
  specialization: "",
  experience: 0,
  languages: [""],
  clinicName: "",
  clinicAddress: "",
  consultationFee: 0,
  consultationType: "",
  workingDays: [""],
  workingHours: [""],
  breakTime: [""],
  reviewCount: 0,
  awards: [""],
});
