export enum NotificationType {
  APPOINTMENT = "APPOINTMENT",
  PRESCRIPTION = "PRESCRIPTION",
  PAYMENT = "PAYMENT",
  REVIEW = "REVIEW",
  REMINDER = "REMINDER",
  SYSTEM = "SYSTEM",
  CHAT = "CHAT",
}
